version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  clamav:
    image: clamav/clamav:latest
    container_name: clamav-daemon
    ports:
      - "3310:3310"
    restart: unless-stopped

  submission:
    build: ./services/submission
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./logs/submission:/var/log/mvp-scanner
    depends_on:
      - redis
      - minio
      - clamav

  static-worker:
    build: ./services/static-worker
    env_file:
      - ./config/.env
    volumes:
      - ./logs/worker:/var/log/mvp-scanner
      - ./services/static-worker/rules:/app/rules
    depends_on:
      - redis
      - minio
      - clamav
      - submission

volumes:
  redis_data:
  minio_data:
